### PR TITLE
big rewrite of tutorial, adding notebooks with and without answers. s…

### PR DESCRIPTION
**Pull request by gidden**
…till need to address dask

### CODE REVIEW

**Comment by gidden** [comment]
For @fmaussion and @byersiiasa to take a look. Dask part still isn't there, I want to try to get some data from IIASA tomorrow.

**Comment by fmaussion** [comment]
Can we merge this or should I start to work on that branch too?

**Comment by fmaussion** [comment]
ok nevermind, working on this notebook now

**Comment by gidden** [comment]
hey @fmaussion, we're finishing up a few things in the dask section now. how doy ou want to proceed?

**Comment by fmaussion** [comment]
I have made cosmetic changes to the sections before dask. Let's merge this first, and see if git can sort this out for us? (I think it will)

**Comment by gidden** [comment]
ok, merged!

**Pull request merged**
